/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SystempulseRouteImport } from './routes/systempulse'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GodmodeRouteImport } from './routes/godmode'
import { Route as GhostvisionRouteImport } from './routes/ghostvision'
import { Route as GhostmodeRouteImport } from './routes/ghostmode'
import { Route as GhostadminRouteImport } from './routes/ghostadmin'
import { Route as CinematicmodeRouteImport } from './routes/cinematicmode'
import { Route as IndexRouteImport } from './routes/index'

const SystempulseRoute = SystempulseRouteImport.update({
  id: '/systempulse',
  path: '/systempulse',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GodmodeRoute = GodmodeRouteImport.update({
  id: '/godmode',
  path: '/godmode',
  getParentRoute: () => rootRouteImport,
} as any)
const GhostvisionRoute = GhostvisionRouteImport.update({
  id: '/ghostvision',
  path: '/ghostvision',
  getParentRoute: () => rootRouteImport,
} as any)
const GhostmodeRoute = GhostmodeRouteImport.update({
  id: '/ghostmode',
  path: '/ghostmode',
  getParentRoute: () => rootRouteImport,
} as any)
const GhostadminRoute = GhostadminRouteImport.update({
  id: '/ghostadmin',
  path: '/ghostadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const CinematicmodeRoute = CinematicmodeRouteImport.update({
  id: '/cinematicmode',
  path: '/cinematicmode',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cinematicmode': typeof CinematicmodeRoute
  '/ghostadmin': typeof GhostadminRoute
  '/ghostmode': typeof GhostmodeRoute
  '/ghostvision': typeof GhostvisionRoute
  '/godmode': typeof GodmodeRoute
  '/login': typeof LoginRoute
  '/systempulse': typeof SystempulseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cinematicmode': typeof CinematicmodeRoute
  '/ghostadmin': typeof GhostadminRoute
  '/ghostmode': typeof GhostmodeRoute
  '/ghostvision': typeof GhostvisionRoute
  '/godmode': typeof GodmodeRoute
  '/login': typeof LoginRoute
  '/systempulse': typeof SystempulseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cinematicmode': typeof CinematicmodeRoute
  '/ghostadmin': typeof GhostadminRoute
  '/ghostmode': typeof GhostmodeRoute
  '/ghostvision': typeof GhostvisionRoute
  '/godmode': typeof GodmodeRoute
  '/login': typeof LoginRoute
  '/systempulse': typeof SystempulseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cinematicmode'
    | '/ghostadmin'
    | '/ghostmode'
    | '/ghostvision'
    | '/godmode'
    | '/login'
    | '/systempulse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cinematicmode'
    | '/ghostadmin'
    | '/ghostmode'
    | '/ghostvision'
    | '/godmode'
    | '/login'
    | '/systempulse'
  id:
    | '__root__'
    | '/'
    | '/cinematicmode'
    | '/ghostadmin'
    | '/ghostmode'
    | '/ghostvision'
    | '/godmode'
    | '/login'
    | '/systempulse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CinematicmodeRoute: typeof CinematicmodeRoute
  GhostadminRoute: typeof GhostadminRoute
  GhostmodeRoute: typeof GhostmodeRoute
  GhostvisionRoute: typeof GhostvisionRoute
  GodmodeRoute: typeof GodmodeRoute
  LoginRoute: typeof LoginRoute
  SystempulseRoute: typeof SystempulseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/systempulse': {
      id: '/systempulse'
      path: '/systempulse'
      fullPath: '/systempulse'
      preLoaderRoute: typeof SystempulseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godmode': {
      id: '/godmode'
      path: '/godmode'
      fullPath: '/godmode'
      preLoaderRoute: typeof GodmodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghostvision': {
      id: '/ghostvision'
      path: '/ghostvision'
      fullPath: '/ghostvision'
      preLoaderRoute: typeof GhostvisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghostmode': {
      id: '/ghostmode'
      path: '/ghostmode'
      fullPath: '/ghostmode'
      preLoaderRoute: typeof GhostmodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghostadmin': {
      id: '/ghostadmin'
      path: '/ghostadmin'
      fullPath: '/ghostadmin'
      preLoaderRoute: typeof GhostadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cinematicmode': {
      id: '/cinematicmode'
      path: '/cinematicmode'
      fullPath: '/cinematicmode'
      preLoaderRoute: typeof CinematicmodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CinematicmodeRoute: CinematicmodeRoute,
  GhostadminRoute: GhostadminRoute,
  GhostmodeRoute: GhostmodeRoute,
  GhostvisionRoute: GhostvisionRoute,
  GodmodeRoute: GodmodeRoute,
  LoginRoute: LoginRoute,
  SystempulseRoute: SystempulseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
