/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GodmodeRouteImport } from './routes/godmode'
import { Route as GhostvisionRouteImport } from './routes/ghostvision'
import { Route as GhostadminRouteImport } from './routes/ghostadmin'
import { Route as IndexRouteImport } from './routes/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GodmodeRoute = GodmodeRouteImport.update({
  id: '/godmode',
  path: '/godmode',
  getParentRoute: () => rootRouteImport,
} as any)
const GhostvisionRoute = GhostvisionRouteImport.update({
  id: '/ghostvision',
  path: '/ghostvision',
  getParentRoute: () => rootRouteImport,
} as any)
const GhostadminRoute = GhostadminRouteImport.update({
  id: '/ghostadmin',
  path: '/ghostadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ghostadmin': typeof GhostadminRoute
  '/ghostvision': typeof GhostvisionRoute
  '/godmode': typeof GodmodeRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ghostadmin': typeof GhostadminRoute
  '/ghostvision': typeof GhostvisionRoute
  '/godmode': typeof GodmodeRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ghostadmin': typeof GhostadminRoute
  '/ghostvision': typeof GhostvisionRoute
  '/godmode': typeof GodmodeRoute
  '/login': typeof LoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ghostadmin' | '/ghostvision' | '/godmode' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ghostadmin' | '/ghostvision' | '/godmode' | '/login'
  id: '__root__' | '/' | '/ghostadmin' | '/ghostvision' | '/godmode' | '/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GhostadminRoute: typeof GhostadminRoute
  GhostvisionRoute: typeof GhostvisionRoute
  GodmodeRoute: typeof GodmodeRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/godmode': {
      id: '/godmode'
      path: '/godmode'
      fullPath: '/godmode'
      preLoaderRoute: typeof GodmodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghostvision': {
      id: '/ghostvision'
      path: '/ghostvision'
      fullPath: '/ghostvision'
      preLoaderRoute: typeof GhostvisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghostadmin': {
      id: '/ghostadmin'
      path: '/ghostadmin'
      fullPath: '/ghostadmin'
      preLoaderRoute: typeof GhostadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GhostadminRoute: GhostadminRoute,
  GhostvisionRoute: GhostvisionRoute,
  GodmodeRoute: GodmodeRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
